import test from 'node:test';
import assert from 'node:assert/strict';
import {DatabaseSync} from 'node:sqlite';
import {createHash} from 'node:crypto';
import {createBookings,validateBooking,moscowDate} from './bookings.mjs';
import {receiptContact} from './receipt.mjs';
import {paymentParams} from './payment.mjs';
const now=Date.parse('2026-09-24T07:00:00Z');
function setup(){const db=new DatabaseSync(':memory:');let clock=now;return {db,b:createBookings(db,()=>clock),advance(n){clock+=n;}};}
const data={name:'Test',contact:'test@example.com',service:'tarot',ageConfirmed:true,offer:true,consent:true,appointmentDate:'2026-09-25',appointmentTime:'11:00'};
test('Moscow boundary, weekdays, past dates and 90 day window',()=>{const {db,b}=setup();assert.equal(moscowDate(Date.parse('2026-09-24T22:00Z')),'2026-09-25');assert.deepEqual(b.availability('2026-09-26').times,[]);assert.deepEqual(b.availability('2026-09-27').times,[]);assert.deepEqual(b.availability('2026-09-23').times,[]);assert.deepEqual(b.availability('2027-01-01').times,[]);assert.throws(()=>b.availability('2026-02-30'));assert.equal(b.availability('2026-09-25').times.length,4);db.close();});
test('unique slots, daily cap of three, cancellation releases space',()=>{const {db,b}=setup();let id;for(const time of ['11:00','13:00','15:00'])id=b.atomic(()=>b.reserve({...data,appointmentTime:time}));assert.throws(()=>b.atomic(()=>b.reserve(data)));assert.deepEqual(b.availability(data.appointmentDate).times,[]);assert.throws(()=>b.atomic(()=>b.reserve({...data,appointmentTime:'17:00'})));b.adminChange({action:'cancel',id});assert.deepEqual(b.availability(data.appointmentDate).times,['15:00','17:00']);db.close();});
test('pause survives store recreation and blocks writes',()=>{const {db,b}=setup();b.adminChange({action:'pause',accepting:false});assert.equal(createBookings(db,()=>now).accepting(),false);assert.throws(()=>b.atomic(()=>b.reserve(data)),/Временно/);b.adminChange({action:'pause',accepting:true});assert.ok(b.atomic(()=>b.reserve(data)));db.close();});
test('reschedule checks conflicts and preserves existing booking on failure',()=>{const {db,b}=setup();const id=b.atomic(()=>b.reserve(data));b.atomic(()=>b.reserve({...data,appointmentTime:'13:00'}));assert.throws(()=>b.adminChange({action:'reschedule',id,date:data.appointmentDate,time:'13:00'}));assert.equal(b.list().find(x=>x.id===id).time,'11:00');b.adminChange({action:'reschedule',id,date:data.appointmentDate,time:'15:00'});assert.equal(b.list().find(x=>x.id===id).time,'15:00');db.close();});
test('unpaid holds expire but paid reservations remain',()=>{const {db,b,advance}=setup();b.atomic(()=>b.reserve(data,1));advance(31*60000);assert.throws(()=>b.requireReservation(1));assert.ok(b.availability(data.appointmentDate).times.includes('11:00'));b.atomic(()=>b.reserve(data,2));b.atomic(()=>b.paid(2));advance(3600000);assert.equal(b.requireReservation(2).status,'confirmed');db.close();});
test('receipt selection validates and discards unrelated contact',()=>{assert.deepEqual(receiptContact({receiptMethod:'sms',phone:'8 (900) 123-45-67',email:'unused@test.com'}),{receiptMethod:'sms',phone:'+79001234567'});assert.deepEqual(receiptContact({receiptMethod:'email',email:'a@b.ru',phone:'+79001234567'}),{receiptMethod:'email',email:'a@b.ru'});assert.throws(()=>receiptContact({receiptMethod:'sms',phone:'123'}));assert.throws(()=>receiptContact({receiptMethod:'email',email:'bad'}));assert.throws(()=>receiptContact({receiptMethod:'other'}));});
test('Robokassa test fields carry signed selected receipt contact',()=>{const order={id:7,amount:4000};const p=paymentParams(order,{receiptMethod:'sms',phone:'+79001234567'},'test','secret');assert.equal(p.Email,undefined);assert.equal(p.Shp_receipt_method,'sms');assert.equal(p.Shp_receipt_contact,'+79001234567');assert.equal(p.IsTest,'1');assert.equal(p.SignatureValue,createHash('sha256').update('test:4000.00:7:secret:Shp_receipt_contact=+79001234567:Shp_receipt_method=sms').digest('hex'));});
test('booking requires separate consents and age',()=>{for(const key of ['ageConfirmed','offer','consent'])assert.throws(()=>validateBooking({...data,[key]:false}));assert.equal(validateBooking(data).legal,'2026-09-24');});
